development:
  adapter: postgresql
  encoding: utf8
  username: manik
  password: secret
  database: manage_list_app_dev

test:
  adapter: postgresql
  encoding: utf8
  username: manik
  password: secret
  database: manage_list_app_test

